// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTbv7xOMiP8lRXrWE-B4jK5JGLrA20_rk',
    appId: '1:695188268049:web:bb7149df4b8b5fbe6b3db0',
    messagingSenderId: '695188268049',
    projectId: 'servicelink-fedaf',
    authDomain: 'servicelink-fedaf.firebaseapp.com',
    storageBucket: 'servicelink-fedaf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-YvbVh35NiaBO7N-CN93mFR0Ia5jP9-M',
    appId: '1:695188268049:android:4870beee537ba3ff6b3db0',
    messagingSenderId: '695188268049',
    projectId: 'servicelink-fedaf',
    storageBucket: 'servicelink-fedaf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxt65fJCoJ1k-jVdZVkW5fwE9n-b6TJN0',
    appId: '1:695188268049:ios:fa68bc5870058db46b3db0',
    messagingSenderId: '695188268049',
    projectId: 'servicelink-fedaf',
    storageBucket: 'servicelink-fedaf.firebasestorage.app',
    iosBundleId: 'com.example.servicelink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxt65fJCoJ1k-jVdZVkW5fwE9n-b6TJN0',
    appId: '1:695188268049:ios:fa68bc5870058db46b3db0',
    messagingSenderId: '695188268049',
    projectId: 'servicelink-fedaf',
    storageBucket: 'servicelink-fedaf.firebasestorage.app',
    iosBundleId: 'com.example.servicelink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTbv7xOMiP8lRXrWE-B4jK5JGLrA20_rk',
    appId: '1:695188268049:web:e1f70e3768441dda6b3db0',
    messagingSenderId: '695188268049',
    projectId: 'servicelink-fedaf',
    authDomain: 'servicelink-fedaf.firebaseapp.com',
    storageBucket: 'servicelink-fedaf.firebasestorage.app',
  );
}
